version: '2'
services:
  db:
    image: mysql:latest
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123654
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: wordpressadmin
      MYSQL_PASSWORD: 123

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - "./.data/wordpress:/var/www/html"
    links:
      - db
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpressadmin
      WORDPRESS_DB_PASSWORD: 123
      WORDPRESS_DB_NAME: wordpressdb